### ISSUE TITLE
Project status and documentation

### ISSUE THREAD

**Issue by DarkMuesli** [hzck/speedroute#3]
Hi! Not sure if this is the right place to ask, but I'll try.

I want to take a look into algorithmic speedrun routing and was curious if you can give me some insights.
What is the status on this project? Are there plans to continue it?

Either way, do you have any documentation on what your concept for model and algorithm is like?
Did you find any major challenges that you may or may not have been able to master?
I'd be happy for any answer, or even slight pointers.

**Comment by hzck** [comment]
Hello,

This is as good a place as any, I think.

The project is on hold as of now. I have been working on it when I feel like it, but I have not done any work the past 8 months or so. It started as a project for me to learn golang but quickly escalated to other stuff I needed to get it running, like creating a web application for it and setting up an https server etc. I even had it running online on speedroute.xyz for a year or so.

My main interest was to get the actual algorithm to work and perform, but I usually get stalled doing other things and then get tired and shut it down for some time. Last I worked on it I managed to setup a database with version handling, password hashing and got stuck when trying to implement the login/register screen in react. I will probably work on it again, but don't know when.

The model is somewhat explained here:
https://htmlpreview.github.io/?https://github.com/hzck/speedroute/blob/master/old-public/howto.html

The algorithm is pretty straight forward:

1. Calculate min path from all nodes to end node (no requirements)
   * Backwards Dijkstra's algorithm from end node to all other nodes, storing value internally for each node (min path left)
1. Create empty priority queue
1. Set start node to current node
1. (LOOP) For all edges in current node, do
   * If edge meets requirements
      1. If start node, create empty path
      1. Add edge to path
      1. Add shortest possible weight (based on rewards and requirements) to path length, 0 if no weight
      1. Add to node's rewards to path
      1. Add path to priority queue, sorted by path length + to node's min path left
1. Choose and remove first path from priority queue
1. Get current node from path (last edge to node)
1. If current node is end node
   * Shortest path has been found, stop
1. Else return from LOOP

It's basically just an improved greedy brute forcing algorithm, and will always give the optimal solution. The code has some logic to identify and mitigate "dangerous" patterns, to improve most use cases. However performance wise I think it is quite easy to break, and I don't know how large of a graph it's able to solve. I read up on some graph theory last year and I think the algorithm as is will not be able to perform well even on smaller graphs. It will probably quickly add up to an insane amount of possible paths, at least if the game has some sort of flexibility (otherwise it would probably be trivial to route it, also).

I had an idea to test it on SM64 16-star or 70-star category, but didn't get that far unfortunately since it's such a hassle to model the graph without a GUI. I think that can be a good candidate to really try out the algorithm since it will require handling both the problem of taking 16/70 starts out of 120 but also that some are not available at all times due to level requirements. Plus the fact that moving around the castle will take time so it might be better to stay at one level and grab more stars instead of grabbing the fastests 16/70 stars.

Nice of you to reach out, I hope I gave some clarity at least!

**Comment by DarkMuesli** [comment]
Thanks a bunch for the info and for taking the time to outline your approach! Defenitely helped me already.
If you are interested, I compiled my own thoughts about the topic in a (yet) unpublished paper:
[https://arxiv.org/abs/2106.01182](https://arxiv.org/abs/2106.01182)
Didn't really test anything, only theory so far. Maybe it even helps. :)

Is there a way to reach out for you aside from GitHub issues and without needing one of us to reveal contact info in a public issue? Just in case more questions arise that I think you can contribute to.

**Comment by hzck** [comment]
Hey Matthias,

I skimmed through the report, I really like that others are also interested in these things! Good luck on finding improvements/solutions to the routing problem! :)

I am myself mostly interested in the algorithm part of the problem, but realized it's very hard to get the data required to really performance test it. To find the timings between each node/state would mean someone need to put in a lot of manual work. I haven't been able to get around that.

With that said I am very interested to see where you end up in the end. You can contact me on speedroute.xyz@gmail.com if you're looking for any further contact. :)

I'm closing this ticket now. Thanks for reaching out!
